apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-container
        image: hello-world-app # Make sure this matches the image name used in the build stage
        ports:
        - containerPort: 80  # Adjust as necessary for your app