apiVersion: apps/v1
kind: Deployment
metadata:
  name: tu-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tu-app
  template:
    metadata:
      labels:
        app: tu-app
    spec:
      containers:
      - name: tu-app
        image: nginx:latest # Imagen base
        ports:
        - containerPort: 80